# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI for Discord Bot

# Triggers the workflow on push or run the workflow using the Actions tab
on:
  push:
  workflow_dispatch:
  #schedule:
    # trigger a build and run of the Discord bot daily at 5 AM PST / 12 PM UTC
    #- cron: '0 12 * * *'

permissions:
  contents: read

jobs:

  build-discord-bot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Set up MariaDB database using Docker
      run: docker run -d -p 3306:3306 -e MYSQL_DATABASE=bot_dev -e MYSQL_ROOT_PASSWORD=rootpw --name mdb103 mariadb:10.3

    - name: install mariadb-connector
      run: |
        sudo apt-get update
        sudo apt install gcc

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install git+https://github.com/Rapptz/discord.py
        pip install requests
        pip install pillow
        pip install selenium
        pip install webdriver-manager
        pip install mariadb

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Set up Google Chrome
      run:  |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable

    - name: Display Google Chrome version
      run: google-chrome --version

    - name: Run Discord Bot
      run:  |
        chmod +x discord-bot.sh
        ./discord-bot.sh ${{ secrets.DISCORD_TOKEN }}
      shell: bash
        
    #- name: Test with pytest
      #run: |
        #pytest
